// File generated by manual extraction from Firebase configs.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_the_flow, constant_identifier_names
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARmuRj3UvK6WDwkX5KN3SmtZTT_XVu18Y',
    appId: '1:387207507333:web:4f6d7e6d97e8e8e8e8e8e8', // Guessed/placeholder for web if not available
    messagingSenderId: '387207507333',
    projectId: 'civicpulse-dev',
    authDomain: 'civicpulse-dev.firebaseapp.com',
    storageBucket: 'civicpulse-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARmuRj3UvK6WDwkX5KN3SmtZTT_XVu18Y',
    appId: '1:387207507333:android:f43e47eec62b54db8268ec',
    messagingSenderId: '387207507333',
    projectId: 'civicpulse-dev',
    storageBucket: 'civicpulse-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKI2fw0ake2vldPhjqOBzk9SKDulTjeD0',
    appId: '1:387207507333:ios:279a63b1af44f5948268ec',
    messagingSenderId: '387207507333',
    projectId: 'civicpulse-dev',
    storageBucket: 'civicpulse-dev.firebasestorage.app',
    iosClientId: '387207507333-o2u7dt1j3tcubgp99qmfh2pgdlh29q4p.apps.googleusercontent.com',
    iosBundleId: 'com.emptylife.civicpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKI2fw0ake2vldPhjqOBzk9SKDulTjeD0',
    appId: '1:387207507333:ios:279a63b1af44f5948268ec',
    messagingSenderId: '387207507333',
    projectId: 'civicpulse-dev',
    storageBucket: 'civicpulse-dev.firebasestorage.app',
    iosClientId: '387207507333-o2u7dt1j3tcubgp99qmfh2pgdlh29q4p.apps.googleusercontent.com',
    iosBundleId: 'com.emptylife.civicpulse',
  );
}
